name: Ecto 
options:
  bundleIdPrefix: com.patrickmick
targets:
  Ecto:
    scheme:
      testTargets:
        - EctoTests 
        - EctoKitTests
        - EctoUITests
      gatherCoverageData: true
    type: application
    platform: tvOS 
    deploymentTarget: "12.0"
    sources: [Ecto]
    dependencies:
      - target: EctoKit 
      - carthage: IGListKit
      - carthage: Kingfisher
  EctoTests:
    type: bundle.unit-test
    platform: tvOS
    sources: [EctoTests]
    settings:
      - TEST_HOST: Ecto
  EctoKit:
    type: framework
    platform: tvOS 
    deploymentTarget: "12.0"
    sources: [EctoKit]
  EctoKitTests:
    type: bundle.unit-test
    platform: tvOS
    sources: [EctoKitTests]
    settings:
      - TEST_HOST: EctoKit
  EctoUITests:
    type: bundle.ui-testing
    platform: tvOS
    sources: [EctoUITests]
    settings:
      - TEST_TARGET_NAME: Ecto
